create table category (
  category_id int not null generated by default as identity,
  name varchar(50),
  parent_id int,
  primary key (category_id),
  CONSTRAINT FK_PARENT FOREIGN KEY (parent_id) REFERENCES category(category_id)
);