INSERT INTO category(category_id, name, parent_id) VALUES
(1, 'Women', null),
    (2, 'Clothing', 1),
        (3, 'Dress', 2),
            (4, 'Casual Dresses', 3),
            (5, 'Party Dresses', 3),
    (6, 'T-Shirts', 1),
        (7, 'Printed T-Shirts', 6),
        (8, 'Casual T-Shirts', 6),
        (9, 'Plain T-Shirts', 6),
(10, 'Men', null),
    (11, 'Footwear', 10),
        (12, 'Branded', 11),
        (13, 'Non-Branded', 11),
    (14, 'T-Shirts', 10),
        (15, 'Printed T-Shirts', 14),
        (16, 'Casual T-Shirts', 14),
        (17, 'Plain T-Shirts', 14),
    (18, 'Shirts', 10),
        (19, 'Party Shirts', 18),
        (20, 'Casual Shirts', 18),
        (21, 'Plain Shirts', 18);